name: Strava Activity Monitor

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-activities:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Check for new Strava activities
      env:
        JOLT_API_URL: ${{ secrets.JOLT_API_URL }}
        JOLT_API_TOKEN: ${{ secrets.JOLT_API_TOKEN }}
      run: |
        python3 cron_strava.py check
    
    - name: Send notifications
      env:
        JOLT_API_URL: ${{ secrets.JOLT_API_URL }}
        JOLT_API_TOKEN: ${{ secrets.JOLT_API_TOKEN }}
      run: |
        python3 cron_strava.py notify
      # Continue even if notifications fail
      continue-on-error: true

  status-check:
    runs-on: ubuntu-latest
    # Run status check only once per hour (at minute 0)
    if: github.event.schedule == '0 * * * *' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Get Strava status
      env:
        JOLT_API_URL: ${{ secrets.JOLT_API_URL }}
        JOLT_API_TOKEN: ${{ secrets.JOLT_API_TOKEN }}
      run: |
        python3 cron_strava.py status
